AppMVC/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using AppMVC.Models;
using Microsoft.AspNet.Identity;

namespace AppMVC.Controllers
{
    public class ReservationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reservations
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Index()
        {
            return View(db.Reservations.ToList());
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
       [Authorize(Roles = "User")]
        public ActionResult Create(int id)
        {
            ViewBag.id = id;
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public ActionResult Create([Bind(Include = "ReservationId,TimeTableId,NumOfTickets")] Reservation reservation)
        {
            reservation.ApplicatinUserId = User.Identity.Name;
            // var timetable = db.Reservations.Include(x=>x.TimeTable).Where(x=>x.TimeTableId == reservation.TimeTableId).FirstOrDefault().TimeTableId;
            // var hall = db.TimeTables.Where(x => x.TimeId == timetable).FirstOrDefault().HallId;
            // Hall h = db.Halls.Find(hall);
            // h.NumOFAvailableSeats = h.NumOFAvailableSeats -reservation.NumOfTickets; ;
            var hall = db.TimeTables.Find(reservation.TimeTableId).HallId;
            var h = db.Halls.Find(hall);
            h.NumOFAvailableSeats = h.NumOFAvailableSeats - reservation.NumOfTickets;
            db.Entry(h).State = EntityState.Modified;
            db.SaveChanges();
            if (ModelState.IsValid)
            {
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("PrintReservations");
            }

            return View(reservation);
        }

        // GET: Reservations/Edit/5
       // [Authorize(Roles = "User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "User")]
        public ActionResult Edit([Bind(Include = "ReservationId,TimeTableId,NumOfTickets,ApplicationUserId")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reservation);
        }

        // GET: Reservations/Delete/5
      //  [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        //[Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [Authorize(Roles = ("User"))]
        public  ActionResult PrintReservations()
        {
            var user = User.Identity.Name;
            var res = db.Reservations.Where(x => x.ApplicatinUserId.ToString() == user.ToString());
            return View(res.ToList());
        }
    }
}

AppMVC/Controllers/TimeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppMVC.Models;

namespace AppMVC.Controllers
{
    public class TimeTablesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TimeTables
        public ActionResult Index( string SearchString)
        {
            var vreme = DateTime.UtcNow;
            var timeTab = db.TimeTables.Where(c => c.Time >= vreme);
            var timeTables = timeTab.Include(t => t.Hall).Include(t => t.Movie);
            
            if (!String.IsNullOrEmpty(SearchString))
            {
                //DateTime vreme = Convert.ToDateTime(SearchString).Date;
                //timeTables = timeTables.Where(v => v.Time.Date == vreme);
                DateTime Search = Convert.ToDateTime(SearchString);
                timeTables = timeTables.Where(r => DbFunctions.TruncateTime(r.Time) == Search.Date);

            }

            return View(timeTables.ToList());
        }

        // GET: TimeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // GET: TimeTables/Create
        [Authorize(Roles = "Editor,Admin")]
        public ActionResult Create()
        {
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName");
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title");
            return View();
        }

        // POST: TimeTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor,Admin")]
        public ActionResult Create([Bind(Include = "TimeId,HallId,MovieId,Time")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                db.TimeTables.Add(timeTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // GET: TimeTables/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // POST: TimeTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Edit([Bind(Include = "TimeId,HallId,MovieId,Time")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // GET: TimeTables/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // POST: TimeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult DeleteConfirmed(int id)
        {
            TimeTable timeTable = db.TimeTables.Find(id);
            db.TimeTables.Remove(timeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppMVC/Views/TimeTables/Create.cshtml
@model AppMVC.Models.TimeTable

@{
    ViewBag.Title = "Create";
}

<h2>Креирај</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Термин за филм</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-2">Сала</div>
            <div class="col-md-10">
                @Html.DropDownList("HallId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HallId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">Филм</div>
            <div class="col-md-10">
                @Html.DropDownList("MovieId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MovieId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">Време</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control datetimepicker", placeholder = "Внеси датум и време" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Креирај" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад кон листата", "Index")
</div>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
   

    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
        $(".datetimepicker").datetimepicker();
    </script>
}

AppMVC/Views/TimeTables/Delete.cshtml
@model AppMVC.Models.TimeTable

@{
    ViewBag.Title = "Delete";
}

<h2>Избриши термин</h2>

<h3>Дали сте сигурни дека сакате да го избришете овој термин?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hall.HallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hall.HallName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Избриши" class="btn btn-danger" /> |
            @Html.ActionLink("Назад кон листата", "Index")
        </div>
    }
</div>

AppMVC/Views/TimeTables/Details.cshtml
@model AppMVC.Models.TimeTable

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>Термини</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Hall.HallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hall.HallName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Едитирај", "Edit", new { id = Model.TimeId }) |
    @Html.ActionLink("Назад кон листата", "Index")
</p>

AppMVC/Views/TimeTables/Edit.cshtml
@model AppMVC.Models.TimeTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TimeTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TimeId)

        <div class="form-group">
            @Html.LabelFor(model => model.HallId, "HallId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HallId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HallId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieId, "MovieId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MovieId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MovieId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppMVC/Views/TimeTables/Index.cshtml
@model IEnumerable<AppMVC.Models.TimeTable>

@{
    ViewBag.Title = "";
    var DistinctItems = Model.GroupBy(x => x.MovieId).Select(y => y.First());


}

<h2>Сите Филмови</h2>
@using (Html.BeginForm())
{
    <div class="row">

        <div style="position: relative" class="col-md-2">
            <input placeholder="Филтрирај по датум" class="form-control datepicker1 " id="SearchString"  name="SearchString" />
        </div>
        <div class="col-md-2">
            <span class=" form-group">
                <input value="Филтрирај" class="btn btn-default" id="filter" type="submit" />
            </span>
        </div>
    </div>
    <div>

    </div>
}
@if (User.IsInRole("Editor") || User.IsInRole("Admin"))
{
<p>
    @Html.ActionLink("Креирај ", "Create")
</p>
}
<table class="table" id="lista">
    @foreach (var item in DistinctItems)
    {
        <tr>
            <td>
                <img src="@Url.Content(item.Movie.ImgUrl)" alt="Image" width="200" height="300" />
            </td>
            <td>
                <h3> @Html.DisplayFor(modelItem => item.Movie.Title)</h3>
                @foreach (var item2 in Model)
                {
                    if (item2.Time.Date >= DateTime.Today.Date)
                    {
                        if (item2.Movie.MovieId == item.Movie.MovieId)
                        {

                        <div class="row">
                            <div class="col-md-3 well">
                                @Html.DisplayFor(modelItem => item2.Hall.HallName)<br />
                                Време @Html.DisplayFor(modelItem => item2.Time.TimeOfDay.Hours): @Html.DisplayFor(modelItem => item2.Time.TimeOfDay.Minutes) <br />
                                Датум   @Html.DisplayFor(modelItem => item2.Time.DayOfWeek)    @Html.DisplayFor(modelItem => item2.Time.Day) /  @Html.DisplayFor(modelItem => item2.Time.Month)
                            </div>
                            <div class="col-md-1">
                                @if (item2.Hall.NumOFAvailableSeats == 0)
                                {
                                    <span class="text-danger">Пополнето</span>
                                }
                                else
                                {
                                    <br />
                                    <div class=" form-group col-md-offset-2 col-md-10">
                                        <button  class="btn btn-default" value="Резервирај" >
                                            @Html.ActionLink( "Резервирај","Create" ,"Reservations", new { id = item2.TimeId} , null) 
                          
                                        </button>
                                    </div>
                                }
                            </div>
                        </div>
                        }
                    }
                }
            </td>

        </tr>
    }

</table>
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="~/Scripts/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datepicker.min.js"></script>
    <script>
        $(".datepicker1").datepicker();
    </script>
    
  
}