AppMVC/Controllers/HomeController.cs
using AppMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppMVC.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var movies = db.TimeTables.Include(m => m.Movie);
            //var max = db.Movies.Select(x => x.Rating).Max();
           // ViewBag.MaxRatingMovie = db.Movies.Where(x => x.Rating == max).Select(x => x.ImgUrl);
           

            return View(movies);
        }

        public ActionResult About()
        {
            ViewBag.Message = " ";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

AppMVC/Controllers/TimeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppMVC.Models;

namespace AppMVC.Controllers
{
    public class TimeTablesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: TimeTables
        public ActionResult Index( string SearchString)
        {
            var vreme = DateTime.UtcNow;
            var timeTab = db.TimeTables.Where(c => c.Time >= vreme);
            var timeTables = timeTab.Include(t => t.Hall).Include(t => t.Movie);
            
            if (!String.IsNullOrEmpty(SearchString))
            {
                //DateTime vreme = Convert.ToDateTime(SearchString).Date;
                //timeTables = timeTables.Where(v => v.Time.Date == vreme);
                DateTime Search = Convert.ToDateTime(SearchString);
                timeTables = timeTables.Where(r => DbFunctions.TruncateTime(r.Time) == Search.Date);

            }

            return View(timeTables.ToList());
        }

        // GET: TimeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // GET: TimeTables/Create
        [Authorize(Roles = "Editor,Admin")]
        public ActionResult Create()
        {
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName");
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title");
            return View();
        }

        // POST: TimeTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Editor,Admin")]
        public ActionResult Create([Bind(Include = "TimeId,HallId,MovieId,Time")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                db.TimeTables.Add(timeTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // GET: TimeTables/Edit/5
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // POST: TimeTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Edit([Bind(Include = "TimeId,HallId,MovieId,Time")] TimeTable timeTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(timeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HallId = new SelectList(db.Halls, "HallId", "HallName", timeTable.HallId);
            ViewBag.MovieId = new SelectList(db.Movies, "MovieId", "Title", timeTable.MovieId);
            return View(timeTable);
        }

        // GET: TimeTables/Delete/5
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TimeTable timeTable = db.TimeTables.Find(id);
            if (timeTable == null)
            {
                return HttpNotFound();
            }
            return View(timeTable);
        }

        // POST: TimeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Editor")]
        public ActionResult DeleteConfirmed(int id)
        {
            TimeTable timeTable = db.TimeTables.Find(id);
            db.TimeTables.Remove(timeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакт";
}
<h2>@ViewBag.Title</h2>



<address>
    

    <strong>Емаил:</strong>   <a href="mailto:gabriela.gorgievska@students.finki.ukim.mk">gabriela.gorgievska@students.finki.ukim.mk</a><br />
    
</address>

AppMVC/Views/Home/Index.cshtml
@model IEnumerable<AppMVC.Models.TimeTable>

@{
    ViewBag.Title = "Home Page";
    double max = 0;
    var maxMovie="";
    foreach(var item in Model)
    {
        if(item.Movie.Rating >= max)
        {
            max = item.Movie.Rating;
            maxMovie = item.Movie.ImgUrl;
        }
    }
    int min = 15000;
    var minCena = "";
    foreach (var item in Model)
    {
        if (item.Movie.PriceForTcket<=min)
        {
           min = item.Movie.PriceForTcket;
            minCena = item.Movie.ImgUrl;
        }
    }

}
<div class="col-md-12">
    <div class="jumbotron" style="text-align:center ; font-size:30px">Проекции на филмови денес</div>
    @foreach (var item in Model)
    {
        if (item.Time.Date == DateTime.Today.Date)
        {
            <a href="@Url.Action("Index", "TimeTables")">
                <img src="@Url.Content(item.Movie.ImgUrl)" alt="Image" width="200" height="300" />
            </a>
        }
    }
</div>
<div class="row">
    
    <div class="col-md-5 panel panel-default panel-body" style="text-align:center">
        <div class=" col-md-12">Најпопуларен филм според рејтинг</div>
        <br />
        <br />
        <a href="@Url.Action("Index", "TimeTables")" >
            <img src="@Url.Content(maxMovie)" alt="Image" width="200" height="300" />
        </a>

    </div>
    <div class="col-md-1"></div>
    <div class="col-md-5  panel panel-default panel-body" style="text-align:center" >
        <div class=" col-md-12">Најефтин филм </div>
        <br/>
        <br/>
        <a href="@Url.Action("Index", "TimeTables")" >
            <img src="@Url.Content(minCena)" alt="Image" width="200" height="300" />
        </a>
    </div>

</div>